[workspace]
members = ["crates/*"]

[workspace.package]
edition = "2024"
rust-version = "1.85"

[package]
name = "fluent-ftl-tools"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[lib]
path = "src/lib.rs"

[[bin]]
name = "check-consistency"
path = "src/bin/check_consistency.rs"

[[bin]]
name = "format"
path = "src/bin/format.rs"

[[bin]]
name = "format-stdin"
path = "src/bin/format_stdin.rs"

[[bin]]
name = "po-convert"
path = "src/bin/po_convert.rs"

[[bin]]
name = "rename"
path = "src/bin/rename.rs"

[[bin]]
name = "show-missing"
path = "src/bin/show_missing.rs"

[dependencies]
fluent = { git = "https://github.com/danielrainer/fluent-rs", rev = "cf712bced280b217b6307edabc2089b3e57204ab" }
fluent-syntax = { git = "https://github.com/danielrainer/fluent-rs", rev = "cf712bced280b217b6307edabc2089b3e57204ab" }
nix = { version = "0.30", features = ["fs"] }
gettext-po-file-parser = { path = "crates/gettext-po-file-parser" }
unic-langid = "0.9.6"
